import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const nunitoMedium = localFont({
  src: "./fonts/Nunito-Medium.ttf",
  variable: "--font-nunito-medium",
  weight: "100 900",
});

const nunitoRegular = localFont({
  src: "./fonts/Nunito-Regular.ttf",
  variable: "--font-nunito-regular",
  weight: "100 900",
});

const nunitoSemiBold = localFont({
  src: "./fonts/Nunito-SemiBold.ttf",
  variable: "--font-nunito-semibold",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${nunitoMedium.variable} ${nunitoRegular.variable} ${nunitoSemiBold.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
